name: event-storming-ui
description: UI für eine Event Storming Session
version: 0.1.0
tech_stack:
  languages:
  - typescript
  - html
  - css
  - node
  frameworks:
  - react
  - tailwind
  databases: []
  tools: []
conventions:
  style_guide: null
  naming_conventions: {}
  file_structure: {}
  testing_strategy: null
structure:
  source_dirs:
  - src
  test_dirs:
  - tests
  doc_dirs:
  - docs
agent_config:
  default_branch: main
  ticket_prefix: TICKET
  auto_commit: true
context:
  important_files: []
  architecture_notes: ''
metadata:
  created_at: '2026-01-30T13:45:13.123990'
  updated_at: '2026-01-30T13:45:13.131633'
